### ISSUE TITLE
Sync rides to Komoot

### ISSUE THREAD

**Issue by spoetnik** [tonithenhausen/karoo-sync#1]
Does this Sync my rides to Komoot?

Thanks

**Comment by tonithenhausen** [comment]
No, only from Komoot to your Karoo. 

I thought that the current Karoo OS update includes sync to Komoot...

**Comment by spoetnik** [comment]
It syncs your routes to the Karoo, not your rides to Komoot.

**Comment by tonithenhausen** [comment]
Yes, sorry :-)
